const employReqs = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    email: "b@beyonce.com",
    phone: "+123 456 789",
    address: "1000 N. Happy Ave.",
    city: "Orlando",
    state: "Florida",
    postalCode: "33922",
    reasonsNotAble: "Ankle injury 4 years ago",
    workExperience: "5 years construction",
    certifications: "Fork lift and Scissor lift certified",
    medicalConditions: "Asthma",
    languages: "English, Spanish, Portuguese",
    expectedPay: "$24/hr",
    currentlyEmployed: "No",
    rightToWork: "Yes",
    workedWithUsBefore: "No",
    canLiftAboveFifty: "Yes",
    liscenceAndVehicle: "Yes",
    willingToTravel: "Yes",
    date: "10/1/2022"
  },
  {
    id: 2,
    firstName: "Jackson",
    lastName: "Doe",
    email: "b@beyonce.com",
    phone: "+123 456 789",
    address: "1000 N. Happy Ave.",
    city: "Orlando",
    state: "Florida",
    postalCode: "33922",
    reasonsNotAble: "Ankle injury 4 years ago",
    workExperience: "5 years construction",
    certifications: "Fork lift and Scissor lift certified",
    medicalConditions: "Asthma",
    languages: "English, Spanish, Portuguese",
    expectedPay: "$24/hr",
    currentlyEmployed: "No",
    rightToWork: "Yes",
    workedWithUsBefore: "No",
    canLiftAboveFifty: "Yes",
    liscenceAndVehicle: "Yes",
    willingToTravel: "Yes",
    date: "10/1/2022"
  },
  {
    id: 3,
    firstName: "Joel",
    lastName: "Doe",
    email: "b@beyonce.com",
    phone: "+123 456 789",
    address: "1000 N. Happy Ave.",
    city: "Orlando",
    state: "Florida",
    postalCode: "33922",
    reasonsNotAble: "Ankle injury 4 years ago",
    workExperience: "5 years construction",
    certifications: "Fork lift and Scissor lift certified",
    medicalConditions: "Asthma",
    languages: "English, Spanish, Portuguese",
    expectedPay: "$24/hr",
    currentlyEmployed: "No",
    rightToWork: "Yes",
    workedWithUsBefore: "No",
    canLiftAboveFifty: "Yes",
    liscenceAndVehicle: "Yes",
    willingToTravel: "Yes",
    date: "10/1/2022"
  },
  {
    id: 4,
    firstName: "Joel",
    lastName: "Doe",
    email: "b@beyonce.com",
    phone: "+123 456 789",
    address: "1000 N. Happy Ave.",
    city: "Orlando",
    state: "Florida",
    postalCode: "33922",
    reasonsNotAble: "Ankle injury 4 years ago",
    workExperience: "5 years construction",
    certifications: "Fork lift and Scissor lift certified",
    medicalConditions: "Asthma",
    languages: "English, Spanish, Portuguese",
    expectedPay: "$24/hr",
    currentlyEmployed: "No",
    rightToWork: "Yes",
    workedWithUsBefore: "No",
    canLiftAboveFifty: "Yes",
    liscenceAndVehicle: "Yes",
    willingToTravel: "Yes",
    date: "10/1/2022"
  },
  {
    id: 5,
    firstName: "Joel",
    lastName: "Doe",
    email: "b@beyonce.com",
    phone: "+123 456 789",
    address: "1000 N. Happy Ave.",
    city: "Orlando",
    state: "Florida",
    postalCode: "33922",
    reasonsNotAble: "Ankle injury 4 years ago",
    workExperience: "5 years construction",
    certifications: "Fork lift and Scissor lift certified",
    medicalConditions: "Asthma",
    languages: "English, Spanish, Portuguese",
    expectedPay: "$24/hr",
    currentlyEmployed: "No",
    rightToWork: "Yes",
    workedWithUsBefore: "No",
    canLiftAboveFifty: "Yes",
    liscenceAndVehicle: "Yes",
    willingToTravel: "Yes",
    date: "10/1/2022"
  },
  {
    id: 6,
    firstName: "Joel",
    lastName: "Doe",
    email: "b@beyonce.com",
    phone: "+123 456 789",
    address: "1000 N. Happy Ave.",
    city: "Orlando",
    state: "Florida",
    postalCode: "33922",
    reasonsNotAble: "Ankle injury 4 years ago",
    workExperience: "5 years construction",
    certifications: "Fork lift and Scissor lift certified",
    medicalConditions: "Asthma",
    languages: "English, Spanish, Portuguese",
    expectedPay: "$24/hr",
    currentlyEmployed: "No",
    rightToWork: "Yes",
    workedWithUsBefore: "No",
    canLiftAboveFifty: "Yes",
    liscenceAndVehicle: "Yes",
    willingToTravel: "Yes",
    date: "10/1/2022"
  }
];

export default employReqs;
